name: cells
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy>=1.22.3
  - matplotlib>=3.5.1
  - pip:
    - autograd
    - git+https://github.com/ninamiolane/geomstats.git@curv-refactor2
    - jupyter
    - mat73
    - numba
    - torch>=1.11
    - -r dev-requirements.txt
