
name: cells
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy>=1.22.3
  - matplotlib>=3.5.1
  - pip:
    - autograd
    - black
    - black[jupyter]
    - flake8
    - flake8-docstrings
    - git+https://github.com/geomstats/geomstats.git
    - isort
    - jupyter
    - mat73
    - pre-commit
